In [2]:
import pandas as pd
data = pd.read_csv('Result.txt')

In [3]:
data

          dataset     method  k    variance  silhouette       bcp       bcr
0            iris  k_medoids  3   30.479524    0.488667  0.834022  0.839360
1            iris     k_mean  3   29.321224    0.499950  0.816085  0.823147
2            wine  k_medoids  3   99.626032    0.291187  0.876889  0.880532
3            wine     k_mean  3   88.730457    0.300015  0.905771  0.907137
4            ILPD  k_medoids  2  180.148026    0.238391  0.591335  0.501986
5            ILPD     k_mean  2  175.949130    0.249043  0.591186  0.497990
6        2Dpoints  k_medoids  4    9.643757    0.580580  0.000000  0.000000
7        2Dpoints     k_mean  4   10.872080    0.537692  0.000000  0.000000
8   seeds_dataset  k_medoids  5   53.381240    0.286039  0.000000  0.000000
9   seeds_dataset     k_mean  5   53.026212    0.298738  0.000000  0.000000
10      BuddyMove  k_medoids  6   69.098034    0.272937  0.000000  0.000000
11      BuddyMove     k_mean  6   66.944518    0.262037  0.000000  0.000000
12  UserKnowledge  k_medoids  6   97.488608    0.184037  0.000000  0.000000
13  UserKnowledge     k_mean  6   93.842958    0.188749  0.000000  0.000000
14            HCV  k_medoids  3  131.381537    0.136323  0.000000  0.000000
15            HCV    k_means  3  128.776094    0.205067  0.000000  0.000000
16    WeeklySales  k_medoids  3  416.430338    0.609201  0.000000  0.000000
17    WeeklySales     k_mean  3  367.785280    0.615093  0.000000  0.000000
18      WholeSale  k_medoids  8   40.934244    0.248893  0.000000  0.000000
19      WholeSale     k_mean  8   42.465385    0.287223  0.000000  0.000000
20   TravelReview  k_medoids  7  333.283892    0.129169  0.000000  0.000000
21   TravelReview     k_mean  7  318.803596    0.143045  0.000000  0.000000

In [15]:
i=0
while i < (len(data)):
    kmed=data.iloc[i]
    i += 1
    kmen=data.iloc[i]
    i += 1
    string = kmed['dataset']+" "
    for j in ['variance','silhouette']:
        string += " & " + str(round(kmen[j],3)) + " & " + str(round(kmed[j],3))
    for j in ['bcp','bcr']:
        if (i<=6):
            string += " & " + str(round(kmen[j],3)) + " & " + str(round(kmed[j],3))
        else:
            string += " & " + "NA" + " & " + "NA"
    print(string,"\\\\")
    print("\hline")

iris  & 29.321 & 30.48 & 0.5 & 0.489 & 0.816 & 0.834 & 0.823 & 0.839 \\
\hline
wine  & 88.73 & 99.626 & 0.3 & 0.291 & 0.906 & 0.877 & 0.907 & 0.881 \\
\hline
ILPD  & 175.949 & 180.148 & 0.249 & 0.238 & 0.591 & 0.591 & 0.498 & 0.502 \\
\hline
2Dpoints  & 10.872 & 9.644 & 0.538 & 0.581 & NA & NA & NA & NA \\
\hline
seeds_dataset  & 53.026 & 53.381 & 0.299 & 0.286 & NA & NA & NA & NA \\
\hline
BuddyMove  & 66.945 & 69.098 & 0.262 & 0.273 & NA & NA & NA & NA \\
\hline
UserKnowledge  & 93.843 & 97.489 & 0.189 & 0.184 & NA & NA & NA & NA \\
\hline
HCV  & 128.776 & 131.382 & 0.205 & 0.136 & NA & NA & NA & NA \\
\hline
WeeklySales  & 367.785 & 416.43 & 0.615 & 0.609 & NA & NA & NA & NA \\
\hline
WholeSale  & 42.465 & 40.934 & 0.287 & 0.249 & NA & NA & NA & NA \\
\hline
TravelReview  & 318.804 & 333.284 & 0.143 & 0.129 & NA & NA & NA & NA \\
\hline